name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: setting-jdk17
      uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'zulu'
    
    - name: checkout
      uses: actions/checkout@v2

    - name: test
      run: ./gradlew clean test
      
    - name: ssh access to ec2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/ubuntu/projects/hanpyeon-academy
          git pull origin main
          ./gradlew build 
          sudo chmod 100 build/libs/academyapi-0.0.1-SNAPSHOT-plain.jar
          sudo chmod 100 build/libs/academyapi-0.0.1-SNAPSHOT.jar
          
          sudo nohup java -jar build/libs/academyapi-0.0.1-SNAPSHOT.jar &
          exit
          
          
        
