name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: setting-jdk17
      uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'zulu'
    
    - name: checkout
      uses: actions/checkout@v2

    - name: test
      run: ./gradlew clean test
      
    - name : build
      run: ./gradlew build

    - name: copy file to server via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_HOST_DEPLOY }}
        username: ${{ secrets.AWS_USERNAME_DEPLOY }}
        key: ${{ secrets.AWS_SSH_KEY_DEPLOY }}
        source: "build/libs/*"
        target: "/home/ubuntu/apiserver"
        
    - name: ssh access to ec2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST_DEPLOY }}
        username: ${{ secrets.AWS_USERNAME_DEPLOY }}
        key: ${{ secrets.AWS_SSH_KEY_DEPLOY }}
        script: |
          sudo systemctl restart apiserver.service
