name: PR TEST

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setting-jdk17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: checkout
        uses: actions/checkout@v2
        
      - name: execute TestCode
        run: ./gradlew clean test